[package]
name = "signal-dbus-client"
version = "0.1.0"
authors = ["Tomas Drtina <tm.drtina@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libsignal-protocol = { git = "https://github.com/signalapp/libsignal-client.git", tag = "v0.8.2" }
signal-provisioning-api = { path = "../signal-provisioning-api" }
#signal-provisioning-api = { git = "https://github.com/tm-drtina/signal-provisioning-api.git" }

rand = "0.7.3"
tungstenite = "^0.13.0"
rustls = "^0.19.1"
webpki = "^0.21.4"

qrcode = "0.12.0"
serde = "*"
serde_json = "*"
base64 = "*"